Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/lib/python3.11/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/lib/python3.11/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/lib/python3.11/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def test_kollisjon():
    """Tester kollisjonsfunksjonen for tilfelle der v = 0, V = -1, m = 1, M = 1.
    Da skal v_neste = -1 og V_neste = 0. Gir en feilmelding hvis dette ikke stemmer.
    """
    v = 0
    V = -1
    m = 1
    M = 1
    v_neste, V_neste = kollisjon(v, V, m, M)
    assert v_neste == -1 and V_neste == 0, "Feil i kollisjon(v, V, m, M). Testen feilet for v = 0, V = -1, m = 1, M = 1."

    v = 1
    V = 0
    m = 1
    M = 1
    v_neste, V_neste = kollisjon(v, V, m, M)
    assert v_neste == 0 and V_neste == 1, "Feil i kollisjon(v, V, m, M). Testen feilet for v = 1, V = 0, m = 1, M = 1."
test_kollisjon()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 18[0m
[1;32m     16[0m     v_neste, V_neste [38;5;241m=[39m kollisjon(v, V, m, M)
[1;32m     17[0m     [38;5;28;01massert[39;00m v_neste [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mand[39;00m V_neste [38;5;241m==[39m [38;5;241m1[39m, [38;5;124m"[39m[38;5;124mFeil i kollisjon(v, V, m, M). Testen feilet for v = 1, V = 0, m = 1, M = 1.[39m[38;5;124m"[39m
[0;32m---> 18[0m [43mtest_kollisjon[49m[43m([49m[43m)[49m

Cell [0;32mIn[2], line 10[0m, in [0;36mtest_kollisjon[0;34m()[0m
[1;32m      8[0m M [38;5;241m=[39m [38;5;241m1[39m
[1;32m      9[0m v_neste, V_neste [38;5;241m=[39m kollisjon(v, V, m, M)
[0;32m---> 10[0m [38;5;28;01massert[39;00m v_neste [38;5;241m==[39m [38;5;241m-[39m[38;5;241m1[39m [38;5;129;01mand[39;00m V_neste [38;5;241m==[39m [38;5;241m0[39m, [38;5;124m"[39m[38;5;124mFeil i kollisjon(v, V, m, M). Testen feilet for v = 0, V = -1, m = 1, M = 1.[39m[38;5;124m"[39m
[1;32m     12[0m v [38;5;241m=[39m [38;5;241m1[39m
[1;32m     13[0m V [38;5;241m=[39m [38;5;241m0[39m

[0;31mAssertionError[0m: Feil i kollisjon(v, V, m, M). Testen feilet for v = 0, V = -1, m = 1, M = 1.
AssertionError: Feil i kollisjon(v, V, m, M). Testen feilet for v = 0, V = -1, m = 1, M = 1.

